"""devices and ac modes

Revision ID: 395b8e3c3fe3
Revises: b7a542cfbcac
Create Date: 2026-09-21 13:49:59.846153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '395b8e3c3fe3'
down_revision: Union[str, Sequence[str], None] = 'b7a542cfbcac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('ha_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reported_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_indoor_id'), 'devices', ['indoor_id'], unique=False)
    op.create_index(op.f('ix_devices_token_hash'), 'devices', ['token_hash'], unique=False)
    op.add_column('indoors', sa.Column('humidifier_mode', sa.Text(), server_default='auto', nullable=False))
    op.add_column('indoors', sa.Column('ac', sa.Boolean(), nullable=True))
    op.add_column('indoors', sa.Column('ac_mode', sa.Text(), server_default='auto', nullable=False))
    op.add_column('indoors', sa.Column('ac_on_above_temp', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('indoors', sa.Column('ac_off_below_temp', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('indoors', sa.Column('ac_hvac_mode', sa.Text(), server_default='cool', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indoors', 'ac_hvac_mode')
    op.drop_column('indoors', 'ac_off_below_temp')
    op.drop_column('indoors', 'ac_on_above_temp')
    op.drop_column('indoors', 'ac_mode')
    op.drop_column('indoors', 'ac')
    op.drop_column('indoors', 'humidifier_mode')
    op.drop_index(op.f('ix_devices_token_hash'), table_name='devices')
    op.drop_index(op.f('ix_devices_indoor_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
