"""indoor pump

Revision ID: 4fc2fb92c629
Revises: 76508d555962
Create Date: 2026-09-23 17:24:27.756518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc2fb92c629'
down_revision: Union[str, Sequence[str], None] = '76508d555962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoors', sa.Column('pump', sa.Boolean(), server_default='false', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indoors', 'pump')
    # ### end Alembic commands ###
