"""fertilizers, plans, applications

Revision ID: 625ac4bd23b3
Revises: dfc969e63712
Create Date: 2026-09-20 19:28:36.149224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '625ac4bd23b3'
down_revision: Union[str, Sequence[str], None] = 'dfc969e63712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('default_amount', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fertilizers_user_id'), 'fertilizers', ['user_id'], unique=False)
    op.create_table('indoor_fertilizer_plan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_id', sa.UUID(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indoor_fertilizer_plan_fertilizer_id'), 'indoor_fertilizer_plan', ['fertilizer_id'], unique=False)
    op.create_index(op.f('ix_indoor_fertilizer_plan_indoor_id'), 'indoor_fertilizer_plan', ['indoor_id'], unique=False)
    op.create_index('uq_indoor_fertilizer_plan', 'indoor_fertilizer_plan', ['indoor_id', 'fertilizer_id'], unique=True)
    op.create_table('fertilizer_applications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('fertilizer_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('watering_history_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watering_history_id'], ['watering_history.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fertilizer_applications_indoor_ts', 'fertilizer_applications', ['indoor_id', sa.literal_column('applied_at DESC')], unique=False)
    op.create_index(op.f('ix_fertilizer_applications_applied_at'), 'fertilizer_applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_fertilizer_applications_fertilizer_id'), 'fertilizer_applications', ['fertilizer_id'], unique=False)
    op.create_index(op.f('ix_fertilizer_applications_indoor_id'), 'fertilizer_applications', ['indoor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fertilizer_applications_indoor_id'), table_name='fertilizer_applications')
    op.drop_index(op.f('ix_fertilizer_applications_fertilizer_id'), table_name='fertilizer_applications')
    op.drop_index(op.f('ix_fertilizer_applications_applied_at'), table_name='fertilizer_applications')
    op.drop_index('idx_fertilizer_applications_indoor_ts', table_name='fertilizer_applications')
    op.drop_table('fertilizer_applications')
    op.drop_index('uq_indoor_fertilizer_plan', table_name='indoor_fertilizer_plan')
    op.drop_index(op.f('ix_indoor_fertilizer_plan_indoor_id'), table_name='indoor_fertilizer_plan')
    op.drop_index(op.f('ix_indoor_fertilizer_plan_fertilizer_id'), table_name='indoor_fertilizer_plan')
    op.drop_table('indoor_fertilizer_plan')
    op.drop_index(op.f('ix_fertilizers_user_id'), table_name='fertilizers')
    op.drop_table('fertilizers')
    # ### end Alembic commands ###
