"""stage target ranges and measurement ppfd

Revision ID: 6e815affbb4b
Revises: 625ac4bd23b3
Create Date: 2026-09-20 20:09:27.220044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e815affbb4b'
down_revision: Union[str, Sequence[str], None] = '625ac4bd23b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurements', sa.Column('ppfd', sa.Integer(), nullable=True))
    op.add_column('stage_targets', sa.Column('temp_min', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('temp_max', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('humidity_min', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('humidity_max', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('light_height_min', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('light_height_max', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('stage_targets', sa.Column('ppfd_min', sa.Integer(), nullable=True))
    op.add_column('stage_targets', sa.Column('ppfd_max', sa.Integer(), nullable=True))
    op.add_column('stage_targets', sa.Column('light_schedule', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stage_targets', 'light_schedule')
    op.drop_column('stage_targets', 'ppfd_max')
    op.drop_column('stage_targets', 'ppfd_min')
    op.drop_column('stage_targets', 'light_height_max')
    op.drop_column('stage_targets', 'light_height_min')
    op.drop_column('stage_targets', 'humidity_max')
    op.drop_column('stage_targets', 'humidity_min')
    op.drop_column('stage_targets', 'temp_max')
    op.drop_column('stage_targets', 'temp_min')
    op.drop_column('measurements', 'ppfd')
    # ### end Alembic commands ###
