"""ac not null

Revision ID: 76508d555962
Revises: 395b8e3c3fe3
Create Date: 2026-09-21 14:39:58.199945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76508d555962'
down_revision: Union[str, Sequence[str], None] = '395b8e3c3fe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("UPDATE indoors SET ac = false WHERE ac IS NULL")
    op.alter_column('indoors', 'ac',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indoors', 'ac',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
