"""humidifier thresholds

Revision ID: 7ebca76fd98e
Revises: af07c6fcd5e2
Create Date: 2026-09-21 08:46:16.177941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebca76fd98e'
down_revision: Union[str, Sequence[str], None] = 'af07c6fcd5e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoors', sa.Column('humidifier_on_below_humidity', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('indoors', sa.Column('humidifier_off_above_humidity', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('indoors', sa.Column('humidifier_on_above_temp', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('indoors', sa.Column('humidifier_off_below_temp', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indoors', 'humidifier_off_below_temp')
    op.drop_column('indoors', 'humidifier_on_above_temp')
    op.drop_column('indoors', 'humidifier_off_above_humidity')
    op.drop_column('indoors', 'humidifier_on_below_humidity')
    # ### end Alembic commands ###
