"""indoor humidifier

Revision ID: af07c6fcd5e2
Revises: ab8fa1e8b0a3
Create Date: 2026-09-21 08:38:24.884176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af07c6fcd5e2'
down_revision: Union[str, Sequence[str], None] = 'ab8fa1e8b0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indoors', sa.Column('humidifier', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indoors', 'humidifier')
    # ### end Alembic commands ###
