"""init schema

Revision ID: ce812b509193
Revises: 
Create Date: 2026-01-20 19:40:58.719639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce812b509193'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_table('indoors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fan_location', sa.Text(), nullable=True),
    sa.Column('extractor_top', sa.Boolean(), nullable=True),
    sa.Column('extractor_bottom', sa.Boolean(), nullable=True),
    sa.Column('fan', sa.Boolean(), nullable=True),
    sa.Column('light_height_cm', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('light_power_pct', sa.Integer(), nullable=True),
    sa.Column('light_schedule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indoors_user_id'), 'indoors', ['user_id'], unique=False)
    op.create_table('indoor_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_indoor_history_indoor_ts', 'indoor_history', ['indoor_id', sa.literal_column('event_ts DESC')], unique=False)
    op.create_index(op.f('ix_indoor_history_event_ts'), 'indoor_history', ['event_ts'], unique=False)
    op.create_index(op.f('ix_indoor_history_indoor_id'), 'indoor_history', ['indoor_id'], unique=False)
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('species', sa.Text(), nullable=True),
    sa.Column('planted_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('watering_interval_days', sa.Integer(), nullable=False),
    sa.Column('default_liters', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('last_watered_at', sa.Date(), nullable=True),
    sa.Column('next_water_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_plants_user_indoor', 'plants', ['user_id', 'indoor_id'], unique=False)
    op.create_index(op.f('ix_plants_indoor_id'), 'plants', ['indoor_id'], unique=False)
    op.create_index(op.f('ix_plants_user_id'), 'plants', ['user_id'], unique=False)
    op.create_table('watering_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('liters', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('ferts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watering_history_plant_ts', 'watering_history', ['plant_id', sa.literal_column('event_ts DESC')], unique=False)
    op.create_index(op.f('ix_watering_history_event_ts'), 'watering_history', ['event_ts'], unique=False)
    op.create_index(op.f('ix_watering_history_plant_id'), 'watering_history', ['plant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watering_history_plant_id'), table_name='watering_history')
    op.drop_index(op.f('ix_watering_history_event_ts'), table_name='watering_history')
    op.drop_index('idx_watering_history_plant_ts', table_name='watering_history')
    op.drop_table('watering_history')
    op.drop_index(op.f('ix_plants_user_id'), table_name='plants')
    op.drop_index(op.f('ix_plants_indoor_id'), table_name='plants')
    op.drop_index('idx_plants_user_indoor', table_name='plants')
    op.drop_table('plants')
    op.drop_index(op.f('ix_indoor_history_indoor_id'), table_name='indoor_history')
    op.drop_index(op.f('ix_indoor_history_event_ts'), table_name='indoor_history')
    op.drop_index('idx_indoor_history_indoor_ts', table_name='indoor_history')
    op.drop_table('indoor_history')
    op.drop_index(op.f('ix_indoors_user_id'), table_name='indoors')
    op.drop_table('indoors')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
