"""watering plans and alerts

Revision ID: dcafb0ab38b3
Revises: 4fc2fb92c629
Create Date: 2026-09-23 17:44:06.148758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcafb0ab38b3'
down_revision: Union[str, Sequence[str], None] = '4fc2fb92c629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('min_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('tolerance_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_rules_indoor_id'), 'alert_rules', ['indoor_id'], unique=False)
    op.create_table('watering_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('mode', sa.Text(), server_default='interval_days', nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=True),
    sa.Column('times_per_day', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('unit', sa.Text(), server_default='L', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watering_plans_indoor_id'), 'watering_plans', ['indoor_id'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), server_default='warning', nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_indoor_ts', 'alerts', ['indoor_id', sa.literal_column('triggered_at DESC')], unique=False)
    op.create_index(op.f('ix_alerts_indoor_id'), 'alerts', ['indoor_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_indoor_id'), table_name='alerts')
    op.drop_index('idx_alerts_indoor_ts', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_watering_plans_indoor_id'), table_name='watering_plans')
    op.drop_table('watering_plans')
    op.drop_index(op.f('ix_alert_rules_indoor_id'), table_name='alert_rules')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
