"""grow stages, ec ph, measurements, tasks

Revision ID: dfc969e63712
Revises: ce812b509193
Create Date: 2026-09-20 18:46:10.920227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfc969e63712'
down_revision: Union[str, Sequence[str], None] = 'ce812b509193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('event_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('runoff_ec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_measurements_indoor_ts', 'measurements', ['indoor_id', sa.literal_column('event_ts DESC')], unique=False)
    op.create_index(op.f('ix_measurements_event_ts'), 'measurements', ['event_ts'], unique=False)
    op.create_index(op.f('ix_measurements_indoor_id'), 'measurements', ['indoor_id'], unique=False)
    op.create_table('stage_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('ec_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ec_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ph_min', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('ph_max', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_targets_indoor_id'), 'stage_targets', ['indoor_id'], unique=False)
    op.create_index('uq_stage_targets_indoor_stage', 'stage_targets', ['indoor_id', 'stage'], unique=True)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('indoor_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=True),
    sa.Column('is_done', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('due_at', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['indoor_id'], ['indoors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tasks_indoor', 'tasks', ['indoor_id', 'is_done'], unique=False)
    op.create_index(op.f('ix_tasks_indoor_id'), 'tasks', ['indoor_id'], unique=False)
    op.add_column('indoors', sa.Column('stage', sa.Text(), server_default='seedling', nullable=False))
    op.add_column('indoors', sa.Column('stage_started_at', sa.Date(), nullable=True))
    op.add_column('watering_history', sa.Column('ec', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('watering_history', sa.Column('ph', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('watering_history', sa.Column('runoff_ec', sa.Numeric(precision=4, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watering_history', 'runoff_ec')
    op.drop_column('watering_history', 'ph')
    op.drop_column('watering_history', 'ec')
    op.drop_column('indoors', 'stage_started_at')
    op.drop_column('indoors', 'stage')
    op.drop_index(op.f('ix_tasks_indoor_id'), table_name='tasks')
    op.drop_index('idx_tasks_indoor', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('uq_stage_targets_indoor_stage', table_name='stage_targets')
    op.drop_index(op.f('ix_stage_targets_indoor_id'), table_name='stage_targets')
    op.drop_table('stage_targets')
    op.drop_index(op.f('ix_measurements_indoor_id'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_event_ts'), table_name='measurements')
    op.drop_index('idx_measurements_indoor_ts', table_name='measurements')
    op.drop_table('measurements')
    # ### end Alembic commands ###
